name: CI
on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env file for CI
      run: cp .github/workflows/.ci.env .env
    - name: Start Docker containers
      run: docker-compose -f .devcontainer/docker-compose.yml up -d
    - name: Install node modules
      run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm ci"
    - name: Linting
      run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm run lint"
    - name: Build
      run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm run build"
    - name: Unit testing
      run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm run test:cov"
    - name: End-to-end testing
      run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm run test:e2e"
    - name: Stop Docker containers
      run: docker-compose -f .devcontainer/docker-compose.yml down