name: CI
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose -f .devcontainer/docker-compose.yml up -d
    - run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm ci"
    - run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm run build"
    - run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm run test:cov"
    - run: docker-compose -f .devcontainer/docker-compose.yml exec -T app /bin/sh -c "cd /workspace; npm run test:e2e"
    - run: docker-compose -f .devcontainer/docker-compose.yml down